service: boxbot
provider:
  name: aws
  runtime: python3.8
  iamRoleStatements:
  - Effect: Allow
    Action:
    - ec2:AssociateIamInstanceProfile
    - ec2:AttachVolume
    - ec2:CreateInstance
    - ec2:CreateTags
    - ec2:DetachVolume
    - ec2:DisassociateIamInstanceProfile
    - ec2:GetConsoleScreenshot
    - ec2:RebootInstances
    - ec2:ReplaceIamInstanceProfileAssociation
    - ec2:RunInstances
    - ec2:StartInstances
    - ec2:StopInstances
    - ec2:TerminateInstances
    Resource:
    - Fn::Join:
      - ':'
      - - arn:aws:ec2
        - !Ref AWS::Region
        - !Ref AWS::AccountId
        - instance/*
    - Fn::Join:
      - ':'
      - - arn:aws:ec2
        - !Ref AWS::Region
        - !Ref AWS::AccountId
        - volume/*
  - Effect: Allow
    Action:
    - ec2:DescribeInstances
    Resource:
    - '*'
package:
  include:
  - boxbot.py
  exclude:
  - .example.env
  - .flake8
  - .github/**
  - .gitignore
  - .venv/**
  - Makefile
  - README.md
  - conftest.py
  - dev-requirements.txt
  - node_modules/**
  - package-lock.json
  - package.json
  - requirements.txt
  - serverless.yml
  - test_boxbot.py
functions:
  list:
    handler: boxbot.list_boxes
    events:
    - http: { path: /, method: get }
  show:
    handler: boxbot.show_box
    events:
    - http: { path: /box, method: get }
  create:
    handler: boxbot.create_box
    events:
    - http: { path: /box, method: post }
  delete:
    handler: boxbot.delete_box
    events:
    - http: { path: /box, method: delete }
