service: boxbot
custom: ${file(${env:BOXBOT_CUSTOM_${opt:stage, 'dev'}, 'empty-custom.yml'})}
provider:
  name: aws
  runtime: python3.8
  apiKeys: ${self:custom.apiKeys}
  iamRoleStatements:
  - Effect: Allow
    Action:
    - apigateway:GET
    Resource: '*'
  - Effect: Allow
    Action:
    - ec2:AssociateIamInstanceProfile
    - ec2:AttachVolume
    - ec2:CreateTags
    - ec2:DetachVolume
    - ec2:DisassociateIamInstanceProfile
    - ec2:GetConsoleScreenshot
    - ec2:RebootInstances
    - ec2:ReplaceIamInstanceProfileAssociation
    - ec2:StartInstances
    - ec2:StopInstances
    - ec2:TerminateInstances
    Resource:
    - Fn::Join:
      - ':'
      - - arn:aws:ec2
        - Ref: AWS::Region
        - Ref: AWS::AccountId
        - instance/*
    - Fn::Join:
      - ':'
      - - arn:aws:ec2
        - !Ref AWS::Region
        - !Ref AWS::AccountId
        - volume/*
  - Effect: Allow
    Action:
    - ec2:CreateInstance
    - ec2:DescribeInstances
    - ec2:RunInstances
    Resource: '*'
package:
  include:
  - boxbot.py
  - basic_auth.py
  exclude:
  - "./**/**"
plugins:
- serverless-basic-authentication
resources:
  Resources:
    GatewayResponse:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.WWW-Authenticate: "'Basic'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: ApiGatewayRestApi
        StatusCode: '401'
functions:
  list:
    handler: boxbot.list_boxes
    events:
    - http: { path: /, method: get, private: true }
  show:
    handler: boxbot.show_box
    events:
    - http:
        path: '/box/{id}'
        method: get
        private: true
        request:
          parameters:
            paths:
              id: true
  create:
    handler: boxbot.create_box
    events:
    - http: { path: /box, method: post, private: true }
  delete:
    handler: boxbot.delete_box
    events:
    - http:
        path: '/box/{id}'
        method: delete
        private: true
        request:
          parameters:
            paths:
              id: true
