service: boxbot
provider:
  name: aws
  runtime: python3.8
package:
  include:
  - boxbot.py
  exclude:
  - .example.env
  - .flake8
  - .github/**
  - .gitignore
  - .venv/**
  - Makefile
  - README.md
  - conftest.py
  - dev-requirements.txt
  - node_modules/**
  - package-lock.json
  - package.json
  - requirements.txt
  - serverless.yml
  - test_boxbot.py
functions:
  list:
    handler: boxbot.list_boxes
    events:
    - http: { path: /, method: get }
  show:
    handler: boxbot.show_box
    events:
    - http: { path: /box, method: get }
  create:
    handler: boxbot.create_box
    events:
    - http: { path: /box, method: post }
  delete:
    handler: boxbot.delete_box
    events:
    - http: { path: /box, method: delete }
